---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit.
shared:
#  image: golang
  # A map of environment variables that we want to set
  environment:
    GOPATH: /sd/workspace
  # annotations to control amount of cpu and ram used
  annotations:
    screwdriver.cd/dockerEnabled: true
    screwdriver.cd/cpu: micro
    screwdriver.cd/ram: micro
# Parameters that can be used in steps, the values provided are defaults
# and can be overridden in the gui at build time
parameters:
  param1: "value1"
  param2:
    value: "value2"
    description: "param2 rocks!"
# Jobs definition block
jobs:
  main:
    image: golang
    requires:
      - ~pr
      - ~commit
    steps:
      # This step downloads and installs packages and dependencies
#      - get: go get -t ./...
#      # The "vet" step runs the go tool vet on packages
#      - vet: go vet ./...
#      # This step runs gofmt on package resources
#      - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
#      # The "test" step tests the packages
#      - test: go test ./...
#      # Compiles the packages and dependencies
#      - build: go build -o filedownloader -a ./...
      # save file to artifact store
      - save: echo hello > $SD_ARTIFACTS_DIR/hello.txt
      - doc: echo $(ls /var/run | grep -i docker)
      # display content of TEST_SECRET as configured in the GUI
      - mysecrets: echo $TEST_SECRET
      # display params
      - parms: 'echo "Param1 $(meta get parameters.param1), Param2 $(meta get parameters.param2.value)"'
      - dock: DOCKER_HOST=tcp://localhost:2375 docker info
      - pack: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.18.1/pack-v0.18.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    # enable secrets used in this pipeline
    secrets:
      - TEST_SECRET
    # setup email notifications
#    settings:
#      email:
#        addresses: [ information@bolbeck.com ]
#        statuses: [ SUCCESS, FAILURE ]
#  sequential:
#    image: node
#    requires:
#      - main
#    steps:
#      - ls: echo $(ls)
#      - parms: 'echo "Param1 $(meta get parameters.param1), Param2 $(meta get parameters.param2.value)"'
#      - dock: DOCKER_HOST=tcp://localhost:2375 docker info
#      - pack: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.18.1/pack-v0.18.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
#  parallel:
#    image: node
#    requires:
#      - ~pr
#      - ~commit
#    steps:
#      - ls: echo $(ls)
#      - parms: 'echo "Param1 $(meta get parameters.param1), Param2 $(meta get parameters.param2.value)"'
#  sequential:
#    image: gcr.io/kaniko-project/executor:debug
#    requires:
#      - main
#    steps:
#      - kanikodir: mkdir -p /kaniko/.docker
#      - ls: echo $(ls)
#      - createconfig: echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
#      - check: cat /kaniko/.docker/config.json
##      - buildimg: /kaniko/executor --context $DOCKER_CONTEXT --dockerfile $DOCKER_DIR/Dockerfile --destination $IMAGE_NAME:$IMAGE_TAG
#    secrets:
#      - REGISTRY_AUTH