---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit.
shared:
  image: golang
  # A map of environment variables that we want to set
  environment:
    GOPATH: /sd/workspace

# Jobs definition block
jobs:
  main:
    requires:
      - ~pr
      - ~commit
    steps:
      # This step downloads and installs packages and dependencies
      - get: go get -t ./...
      # The "vet" step runs the go tool vet on packages
      - vet: go vet ./...
      # This step runs gofmt on package resources
      - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
      # The "test" step tests the packages
      - test: go test ./...
      # Compiles the packages and dependencies
      - build: go build -o fileDownloader -a ./...